# Generated by Django 6.0.5 on 2026-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_analysis_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('model_analysis', 'Model analysis'), ('template_comparison', 'Template comparison'), ('tool_analysis', 'Tool analysis'), ('generation_analytics', 'Generation analytics'), ('comprehensive', 'Comprehensive'), ('experiment_report', 'Experiment report')], max_length=40, verbose_name='type'),
        ),
    ]
