# Generated by Django 6.0.5 on 2026-07-09 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_job_prompt_hash_bundle_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatebundle',
            options={'ordering': ['-is_default', '-is_system', 'name', '-version'], 'verbose_name': 'Template Bundle', 'verbose_name_plural': 'Template Bundles'},
        ),
        migrations.AddField(
            model_name='apprequirementtemplate',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='content hash'),
        ),
        migrations.AddField(
            model_name='apprequirementtemplate',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='', max_length=20, verbose_name='difficulty'),
        ),
        migrations.AddField(
            model_name='apprequirementtemplate',
            name='spec_schema_version',
            field=models.PositiveIntegerField(default=1, verbose_name='spec schema version'),
        ),
        migrations.AddField(
            model_name='apprequirementtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Bumped by the seeder when the spec content changes; single mutable row per slug', verbose_name='version'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='content hash'),
        ),
        migrations.AddField(
            model_name='templatebundle',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='content hash'),
        ),
        migrations.AddField(
            model_name='templatebundle',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hidden from pickers but kept for jobs that reference it', verbose_name='archived'),
        ),
        migrations.AddField(
            model_name='templatebundle',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Versions are immutable: editing a bundle creates version+1', verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='templatebundle',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='templatebundle',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='generation_templatebundle_slug_version_uniq'),
        ),
    ]
