# Generated by Django 6.0.5 on 2026-07-10 05:58

from django.db import migrations, models


def backfill_stack_slug(apps, schema_editor):
    """Copy each job's scaffolding_template.slug onto the new stack_slug field.

    Raw slug, not canonicalized: the old resolve_stack_slug() canonicalized
    scaffolding_template.slug at read time, and the new resolve_stack_slug()
    does the same to stack_slug — copying the raw value preserves identical
    resolved behavior for every existing job.
    """
    generation_job = apps.get_model("generation", "GenerationJob")
    batch = []
    qs = generation_job.objects.exclude(scaffolding_template__isnull=True).only("id", "scaffolding_template")
    for job in qs.select_related("scaffolding_template").iterator(chunk_size=500):
        job.stack_slug = job.scaffolding_template.slug
        batch.append(job)
        if len(batch) >= 500:
            generation_job.objects.bulk_update(batch, ["stack_slug"])
            batch = []
    if batch:
        generation_job.objects.bulk_update(batch, ["stack_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_experiments'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='stack_slug',
            field=models.CharField(blank=True, default='', help_text='Canonical or alias slug from runtime/scaffolding/manifest.json', max_length=100, verbose_name='stack slug'),
        ),
        migrations.RunPython(backfill_stack_slug, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='generationjob',
            name='scaffolding_template',
        ),
        migrations.DeleteModel(
            name='ScaffoldingTemplate',
        ),
    ]
