# Generated by Django 6.0.5 on 2026-07-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0006_remove_generationjob_scaffolding_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationjob',
            name='backend_prompt_template',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='frontend_prompt_template',
        ),
        migrations.DeleteModel(
            name='PromptTemplate',
        ),
    ]
