# Generated by Django 6.0.5 on 2026-07-11 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0008_rename_templatebundle_generationprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationprofile',
            options={'ordering': ['-is_default', '-is_system', 'name', '-version'], 'verbose_name': 'Generation Profile', 'verbose_name_plural': 'Generation Profiles'},
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='bundle_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Denormalized "profile-slug@version" slicing key', max_length=220, verbose_name='bundle key'),
        ),
        migrations.AlterField(
            model_name='generationprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generationprofile',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default profile'),
        ),
        migrations.AlterField(
            model_name='generationprofile',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='system profile'),
        ),
        migrations.AlterField(
            model_name='generationprofile',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Versions are immutable: editing a profile creates version+1', verbose_name='version'),
        ),
    ]
