# Generated by Django 6.0.5 on 2026-07-12 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0002_single_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versions are immutable: content changes create version+1', verbose_name='version')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='builtin')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('is_approved', models.BooleanField(default=True, help_text='Gate for user stacks when STACK_REQUIRE_APPROVAL is on', verbose_name='approved')),
                ('has_frontend', models.BooleanField(default=False, verbose_name='has frontend')),
                ('default_port', models.PositiveIntegerField(default=8000, verbose_name='default port')),
                ('patch_profile', models.CharField(choices=[('flask', 'Flask'), ('none', 'None')], default='none', max_length=20, verbose_name='patch profile')),
                ('frontend_component', models.CharField(blank=True, default='', max_length=100, verbose_name='frontend component')),
                ('backend_filename', models.CharField(default='app.py', max_length=100, verbose_name='backend filename')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='aliases')),
                ('files', models.JSONField(blank=True, default=dict, help_text='Skeleton tree as {relative_path: text}', verbose_name='files')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='content hash')),
                ('dockerfile_mode', models.CharField(choices=[('bundled', 'Bundled'), ('generated', 'Generated')], default='bundled', max_length=20, verbose_name='dockerfile mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
                'ordering': ['slug', '-version'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='runtime_stack_slug_version_uniq')],
            },
        ),
    ]
