# Generated by Django 6.0.5 on 2026-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='backend_base_image',
            field=models.CharField(blank=True, default='', help_text="Must be in settings.STACK_ALLOWED_BASE_IMAGES['python']", max_length=100, verbose_name='backend base image'),
        ),
        migrations.AddField(
            model_name='stack',
            name='frontend_base_image',
            field=models.CharField(blank=True, default='', help_text="Must be in settings.STACK_ALLOWED_BASE_IMAGES['node']", max_length=100, verbose_name='frontend base image'),
        ),
        migrations.AddField(
            model_name='stack',
            name='server_kind',
            field=models.CharField(choices=[('python', 'python <backend_filename>'), ('uvicorn', 'uvicorn app:app')], default='python', help_text='Constrained start command — user stacks cannot run arbitrary CMDs', max_length=20, verbose_name='server kind'),
        ),
    ]
