# Generated by Django 6.0.5 on 2026-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzertool',
            name='sample_filename',
            field=models.CharField(blank=True, default='', help_text="Filename for the sample (for filename-sensitive tools, e.g. 'Dockerfile').", max_length=100, verbose_name='sample filename'),
        ),
    ]
