# Generated by Django 6.0.5 on 2026-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analyzertool_sample_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzertool',
            name='docs_url',
            field=models.URLField(blank=True, default='', verbose_name='documentation URL'),
        ),
    ]
