# Generated by Django 6.0.5 on 2026-07-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analyzertool_docs_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzertool',
            name='output_kind',
            field=models.CharField(choices=[('findings', 'Findings'), ('metrics', 'Metrics'), ('mixed', 'Findings + metrics')], default='findings', help_text='Whether the tool produces discrete findings, aggregate metrics, or both.', max_length=20, verbose_name='output kind'),
        ),
        migrations.AddField(
            model_name='toolresult',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='metrics'),
        ),
    ]
