# Generated by Django 6.0.5 on 2026-06-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('reports', '0002_reconcile_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='analysis_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='analysis.analysisrun'),
        ),
    ]
