# Generated by Django 6.0.5 on 2026-06-19 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0002_content_blocks_and_bundles'),
        ('runtime', '0002_single_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('category', models.CharField(choices=[('security', 'Security'), ('lint', 'Lint / quality'), ('performance', 'Performance'), ('secrets', 'Secrets'), ('ai', 'AI review')], db_index=True, default='lint', max_length=20, verbose_name='category')),
                ('kind', models.CharField(choices=[('container', 'Container CLI'), ('ai', 'AI reviewer')], default='container', max_length=20, verbose_name='kind')),
                ('target_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript / TypeScript'), ('any', 'Any')], default='any', max_length=20, verbose_name='target language')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='icon')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='version')),
                ('install_cmd', models.TextField(blank=True, default='', verbose_name='install command')),
                ('verify_cmd', models.TextField(blank=True, default='', verbose_name='verify command')),
                ('run_cmd', models.TextField(blank=True, default='', help_text="Template; '{target}' is replaced with the code path.", verbose_name='run command')),
                ('parser_key', models.CharField(blank=True, default='', max_length=50, verbose_name='parser key')),
                ('config_schema', models.JSONField(blank=True, default=list, verbose_name='config schema')),
                ('default_config', models.JSONField(blank=True, default=dict, verbose_name='default config')),
                ('run_timeout', models.PositiveIntegerField(default=120, verbose_name='run timeout (s)')),
                ('install_timeout', models.PositiveIntegerField(default=300, verbose_name='install timeout (s)')),
                ('sample_code', models.TextField(blank=True, default='', verbose_name='sample code')),
                ('is_system', models.BooleanField(default=True, verbose_name='system tool')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='enabled')),
                ('display_order', models.IntegerField(default=100, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analyzer Tool',
                'verbose_name_plural': 'Analyzer Tools',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyzerWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('stopped', 'Stopped'), ('error', 'Error')], db_index=True, default='absent', max_length=20, verbose_name='status')),
                ('image', models.CharField(blank=True, default='', max_length=300, verbose_name='image')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzer_workspaces', to='runtime.containerinstance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyzer Workspace',
                'verbose_name_plural': 'Analyzer Workspaces',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                ('source_code', models.JSONField(blank=True, null=True, verbose_name='source code')),
                ('tool_slugs', models.JSONField(blank=True, default=list, verbose_name='tool slugs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partial')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='summary')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='duration (s)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to='generation.generationjob')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='analysis.analyzerworkspace')),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstalledTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('installing', 'Installing'), ('installed', 'Installed'), ('failed', 'Failed')], default='installing', max_length=20, verbose_name='status')),
                ('installed_version', models.CharField(blank=True, default='', max_length=100, verbose_name='installed version')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='config')),
                ('install_log', models.TextField(blank=True, default='', verbose_name='install log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='analysis.analyzertool')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_tools', to='analysis.analyzerworkspace')),
            ],
            options={
                'verbose_name': 'Installed Tool',
                'verbose_name_plural': 'Installed Tools',
                'ordering': ['tool__display_order', 'tool__name'],
            },
        ),
        migrations.CreateModel(
            name='ToolResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_slug', models.CharField(db_index=True, max_length=100, verbose_name='tool slug')),
                ('category', models.CharField(blank=True, default='', max_length=20, verbose_name='category')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='status')),
                ('raw_output', models.JSONField(blank=True, default=dict, verbose_name='raw output')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='summary')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.analysisrun')),
            ],
            options={
                'verbose_name': 'Tool Result',
                'verbose_name_plural': 'Tool Results',
                'ordering': ['tool_slug'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='info', max_length=20, verbose_name='severity')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='category')),
                ('confidence', models.CharField(blank=True, default='medium', max_length=20, verbose_name='confidence')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('suggestion', models.TextField(blank=True, default='', verbose_name='suggestion')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='file path')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='line number')),
                ('column_number', models.IntegerField(blank=True, null=True, verbose_name='column number')),
                ('code_snippet', models.TextField(blank=True, default='', verbose_name='code snippet')),
                ('rule_id', models.CharField(blank=True, default='', max_length=100, verbose_name='rule id')),
                ('tool_specific_data', models.JSONField(blank=True, default=dict, verbose_name='tool specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='analysis.toolresult')),
            ],
            options={
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
                'ordering': ['severity', 'file_path', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['created_by', '-created_at'], name='analysis_an_created_7eaedb_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status'], name='analysis_an_status_84ecd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installedtool',
            unique_together={('workspace', 'tool')},
        ),
        migrations.AlterUniqueTogether(
            name='toolresult',
            unique_together={('run', 'tool_slug')},
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['severity'], name='analysis_fi_severit_569d07_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['rule_id'], name='analysis_fi_rule_id_9a0c45_idx'),
        ),
    ]
