# Generated by Django 6.0.5 on 2026-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysistask_profile_threshold'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='finding',
            new_name='analysis_fi_suppres_f425c9_idx',
            old_name='analysis_fi_suppres_idx',
        ),
        migrations.RenameIndex(
            model_name='finding',
            new_name='analysis_fi_result__865eba_idx',
            old_name='analysis_fi_result_suppres_idx',
        ),
        migrations.AlterField(
            model_name='analysisprofile',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
